apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-sentinel
  namespace: platform-security
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platform-sentinel
  template:
    metadata:
      labels:
        app: platform-sentinel
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: sentinel
          image: busybox:1.36
          command: ["sh", "-c", "while true; do echo 'security ok' && date -u; sleep 30; done"]
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 50m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
